apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  selector:
    app: homebridge
  ports:
    - protocol: TCP
      port: 8581
      targetPort: 8581
  type: LoadBalancer
